"""Create base models for Users and Blog posts

Revision ID: e8e7c8db4702
Revises:
Create Date: 2016-09-28 22:12:15.011902

"""

# revision identifiers, used by Alembic.
revision = 'e8e7c8db4702'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Unicode(length=255), nullable=True),
    sa.Column('last_name', sa.Unicode(length=255), nullable=True),
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.Column('phone', sa.Unicode(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('slug', sa.Unicode(length=280), nullable=False),
    sa.Column('body', sa.UnicodeText(), nullable=True),
    sa.Column('status', sa.Enum('published', 'draft', name='blog_post_statuses'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_blog_post_author_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_post'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_post')
    op.drop_table('users')
    ### end Alembic commands ###
